namespace ModelGenerator.Utils.Tests;

[Trait("Type", "Unit")]
public class ModelsTests : IDisposable
{
  public ModelsTests() { }

  public void Dispose() { }

  [Fact]
  public void AddHeader_ItShouldReturnTheProvidedCodePrependedWithTheExpectedHeader()
  {
    string code = "my code goes here.\nwith a line break";
    string header = $$"""
// ------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Kafka JSON Schema.
//     Root schema title: test schema title
//     This file is intended for use with Confluent.SchemaRegistry.Serdes.Json.
// </auto-generated>
// ------------------------------------------------------------------------------

""";

    Assert.Equal(header + code, ModelGenerator.Utils.Models.AddHeader(code, "test schema title"));
  }

  [Fact]
  public void EnsureRootJsonObjectTitle_ItShouldReturnTheProvidedCodeWithTheExpectedAnotations()
  {
    List<string> code = [
      "something public partial class Hello() { public Hello() {} private bool Test() { return true; } }",
      "  public partial class Yup() { public Yup() {} }",
      "private partial class PClass() { public PClass() {} }",
      "public class PClass() { public PClass() {} }",
    ];
    List<string> expectedCode = [
      "something public partial class Hello() { public Hello() {} private bool Test() { return true; } }",
      "  [Newtonsoft.Json.JsonObject(Title = \"some schema \\\" title\")]\n  public partial class Yup() { public Yup() {} }",
      "private partial class PClass() { public PClass() {} }",
      "public class PClass() { public PClass() {} }",
    ];

    Assert.Equal(
      String.Join("\n", expectedCode),
      ModelGenerator.Utils.Models.EnsureRootJsonObjectTitle(String.Join("\n", code), "some schema \" title")
    );
  }

  [Fact]
  public void EnsurePartialClasses_ItShouldReturnTheProvidedCodeWithTheExpectedPartialKeywords()
  {
    List<string> code = [
      "something public class Hello() { public Hello() {} private bool Test() { return true; } }",
      "  public partial class Yup() { public Yup() {} }",
      "private class PClass() { public PClass() {} }",
      "private partial class PClass() { public PClass() {} }",
    ];
    List<string> expectedCode = [
      "something public class Hello() { public Hello() {} private bool Test() { return true; } }",
      "  public partial class Yup() { public Yup() {} }",
      "private class PClass() { public PClass() {} }",
      "private partial class PClass() { public PClass() {} }",
    ];

    Assert.Equal(
      String.Join("\n", expectedCode),
      ModelGenerator.Utils.Models.EnsurePartialClasses(String.Join("\n", code))
    );
  }

  [Theory]
  [InlineData(null, "KafkaMessage")]
  [InlineData("", "KafkaMessage")]
  [InlineData(" ", "KafkaMessage")]
  [InlineData("\t", "KafkaMessage")]
  [InlineData("\r\n", "KafkaMessage")]
  [InlineData("hello", "Hello")]
  [InlineData("HelloWorld", "HelloWorld")]
  [InlineData("hello world", "HelloWorld")]
  [InlineData("hello-world", "HelloWorld")]
  [InlineData("hello.world", "HelloWorld")]
  [InlineData("hello-world.test value", "HelloWorldTestValue")]
  [InlineData("one--two..three  four", "OneTwoThreeFour")]
  [InlineData("a", "A")]
  [InlineData("a b c", "ABC")]
  [InlineData("order 123 item", "Order123Item")]
  [InlineData("123 abc", "_123Abc")]
  [InlineData("9test", "_9test")]
  [InlineData("!!!@@@###", "KafkaMessage")]
  [InlineData("hello@world#test", "HelloWorldTest")]
  [InlineData("...hello world---", "HelloWorld")]
  [InlineData("hello_world", "Hello_world")]
  [InlineData("___", "___")]
  [InlineData("hello---world___test", "HelloWorld___test")]
  [InlineData("hELLO wORLD", "HELLOWORLD")]
  public void ToPascalCaseIdentifier_ShouldReturnExpectedValue(string? value, string expected)
  {
    Assert.Equal(expected, ModelGenerator.Utils.Models.ToPascalCaseIdentifier(value!));
  }
}
