// ------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Kafka JSON Schema.
//     Root schema title: ShippingNexusKey
//     This file is intended for use with Confluent.SchemaRegistry.Serdes.Json.
// </auto-generated>
// ------------------------------------------------------------------------------
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace Tester.Models.EopItemTrackingShippingNexusV1
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [Newtonsoft.Json.JsonObject(Title = "ShippingNexusKey")]
    public partial class ShippingNexusKey
    {

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Id { get; set; } = default!;

    }
}