// ------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Kafka JSON Schema.
//     Root schema title: EopItemTrackingShippingNexusV1Value
//     This file is intended for use with Confluent.SchemaRegistry.Serdes.Json.
// </auto-generated>
// ------------------------------------------------------------------------------
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace Tester.Models.EopItemTrackingShippingNexusV1
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// This schema uses 'additionalProperties: false' to ensure strict validation by disallowing properties not explicitly defined in the schema.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [Newtonsoft.Json.JsonObject(Title = "EopItemTrackingShippingNexusV1Value")]
    public partial class EopItemTrackingShippingNexusV1Value
    {

        /// <summary>
        /// Message metadata
        /// </summary>
        [Newtonsoft.Json.JsonProperty("metadata", Required = Newtonsoft.Json.Required.Always)]
        public Metadata Metadata { get; set; } = new Metadata();

        /// <summary>
        /// Shipping manifest
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping", Required = Newtonsoft.Json.Required.Always)]
        public Shipping Shipping { get; set; } = new Shipping();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Metadata
    {

        /// <summary>
        /// Global id of the operation that originated this message. Used for tracking the operation on all the services involved
        /// </summary>
        [Newtonsoft.Json.JsonProperty("correlation_id", Required = Newtonsoft.Json.Required.Always)]
        public string Correlation_id { get; set; } = default!;

        /// <summary>
        /// id of the json schema associated with this message
        /// </summary>
        [Newtonsoft.Json.JsonProperty("data_type", Required = Newtonsoft.Json.Required.Always)]
        public string Data_type { get; set; } = default!;

        /// <summary>
        /// Local id of the operation that originated this message. This id is local to the service/microservice that originated the message
        /// </summary>
        [Newtonsoft.Json.JsonProperty("interchange_id", Required = Newtonsoft.Json.Required.Always)]
        public System.Guid Interchange_id { get; set; } = default!;

        /// <summary>
        /// id of the service/microservice that generated this message
        /// </summary>
        [Newtonsoft.Json.JsonProperty("source", Required = Newtonsoft.Json.Required.Always)]
        public string Source { get; set; } = default!;

        /// <summary>
        /// Date when this message was generated
        /// </summary>
        [Newtonsoft.Json.JsonProperty("timestamp", Required = Newtonsoft.Json.Required.Always)]
        public System.DateTimeOffset Timestamp { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Shipping
    {

        /// <summary>
        /// Additional services list in CTT system is equivalent to special services
        /// </summary>
        [Newtonsoft.Json.JsonProperty("additionals", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<additionals> Additionals { get; set; } = new System.Collections.ObjectModel.Collection<additionals>();

        [Newtonsoft.Json.JsonProperty("audit", Required = Newtonsoft.Json.Required.Always)]
        public Audit Audit { get; set; } = new Audit();

        /// <summary>
        /// Code of the client center this manifest is associated with
        /// </summary>
        [Newtonsoft.Json.JsonProperty("client_center_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Client_center_code { get; set; } = default!;

        /// <summary>
        /// Code of the client this manifest is associated with used in CTT - Correios de Portugal systems
        /// </summary>
        [Newtonsoft.Json.JsonProperty("client_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Client_code { get; set; } = default!;

        /// <summary>
        /// Code of the client this manifest is associated with used in CTT Express systems
        /// </summary>
        [Newtonsoft.Json.JsonProperty("client_code_es", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Client_code_es { get; set; } = default!;

        /// <summary>
        /// Shipping client hub code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("client_hub_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Client_hub_code { get; set; } = default!;

        /// <summary>
        /// Client References list
        /// </summary>
        [Newtonsoft.Json.JsonProperty("client_references", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string>? Client_references { get; set; } = default!;

        /// <summary>
        /// Contract code used in CTT Correios de Portugal systems
        /// </summary>
        [Newtonsoft.Json.JsonProperty("contract_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Contract_code { get; set; } = default!;

        /// <summary>
        /// Declared Committed Delivery datetime (ISO 8601)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("declared_committed_delivery_datetime", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? Declared_committed_delivery_datetime { get; set; } = default!;

        /// <summary>
        /// Delivery details
        /// </summary>
        [Newtonsoft.Json.JsonProperty("delivery", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Delivery? Delivery { get; set; } = default!;

        /// <summary>
        /// Shipping destination address (Address where the shipment must be delivered)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_address", Required = Newtonsoft.Json.Required.Always)]
        public string Destin_address { get; set; } = default!;

        /// <summary>
        /// Destination country code (Country where the shipment must be delivered)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_country_code", Required = Newtonsoft.Json.Required.Always)]
        public string Destin_country_code { get; set; } = default!;

        /// <summary>
        /// Shipping destination hub code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_hub_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Destin_hub_code { get; set; } = default!;

        /// <summary>
        /// Name of the destination hub
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_hub_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Destin_hub_name { get; set; } = default!;

        /// <summary>
        /// Destination Name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Destin_name { get; set; } = default!;

        /// <summary>
        /// Destination Postal Code (Postal Code where the shipment must be delivered)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_postal_code", Required = Newtonsoft.Json.Required.Always)]
        public string Destin_postal_code { get; set; } = default!;

        /// <summary>
        /// Shipping destination town name (Town where the shipment must be delivered)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_town_name", Required = Newtonsoft.Json.Required.Always)]
        public string Destin_town_name { get; set; } = default!;

        /// <summary>
        /// Information for devolution process
        /// </summary>
        [Newtonsoft.Json.JsonProperty("devolution", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Devolution? Devolution { get; set; } = default!;

        /// <summary>
        /// Dispash Number used by CTT - Correios de Portugal
        /// </summary>
        [Newtonsoft.Json.JsonProperty("dispatch_number", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Dispatch_number { get; set; } = default!;

        /// <summary>
        /// Expedition code used by CTT - Correios de Portugal
        /// </summary>
        [Newtonsoft.Json.JsonProperty("expedition_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Expedition_code { get; set; } = default!;

        /// <summary>
        /// Indicates that the shipping is a devolution
        /// </summary>
        [Newtonsoft.Json.JsonProperty("is_devolution", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? Is_devolution { get; set; } = false;

        /// <summary>
        /// Indicates that the is a shipment (remessa)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("is_expedition_prime", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? Is_expedition_prime { get; set; } = false;

        /// <summary>
        /// Indicates that the shipping is a return (back)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("is_return", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? Is_return { get; set; } = false;

        /// <summary>
        /// Shipping item list
        /// </summary>
        [Newtonsoft.Json.JsonProperty("items", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<items> Items { get; set; } = new System.Collections.ObjectModel.Collection<items>();

        /// <summary>
        /// Total number of items for this shipping
        /// </summary>
        [Newtonsoft.Json.JsonProperty("items_count", Required = Newtonsoft.Json.Required.Always)]
        public int Items_count { get; set; } = default!;

        /// <summary>
        /// Datetime when the manifest were created
        /// </summary>
        [Newtonsoft.Json.JsonProperty("manifest_datetime", Required = Newtonsoft.Json.Required.Always)]
        public System.DateTimeOffset Manifest_datetime { get; set; } = default!;

        /// <summary>
        /// Origin Address (Address where you have to go to pick up the shipment)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("origin_address", Required = Newtonsoft.Json.Required.Always)]
        public string Origin_address { get; set; } = default!;

        /// <summary>
        /// Origin country code (Country where you have to go to pick up the shipment) ISO-ALFA2
        /// </summary>
        [Newtonsoft.Json.JsonProperty("origin_country_code", Required = Newtonsoft.Json.Required.Always)]
        public string Origin_country_code { get; set; } = default!;

        /// <summary>
        /// Shipping origin hub code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("origin_hub_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Origin_hub_code { get; set; } = default!;

        /// <summary>
        /// Origin Postal Code (Postal Code where you have to go to pick up the shipment)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("origin_postal_code", Required = Newtonsoft.Json.Required.Always)]
        public string Origin_postal_code { get; set; } = default!;

        /// <summary>
        /// The name of the origin town (Town where you have to go to pick up the shipment)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("origin_town_name", Required = Newtonsoft.Json.Required.Always)]
        public string Origin_town_name { get; set; } = default!;

        /// <summary>
        /// Code of the provider
        /// </summary>
        [Newtonsoft.Json.JsonProperty("provider_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Provider_code { get; set; } = default!;

        /// <summary>
        /// Shipping code assigned by the external provider
        /// </summary>
        [Newtonsoft.Json.JsonProperty("provider_shipping_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Provider_shipping_code { get; set; } = default!;

        /// <summary>
        /// Recipient address
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_address { get; set; } = default!;

        /// <summary>
        /// Recipient Country Code. ISO 3166 ALPHA-2 format
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_country_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_country_code { get; set; } = default!;

        /// <summary>
        /// Recipient email address for notifications
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_email_notify_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_email_notify_address { get; set; } = default!;

        /// <summary>
        /// Recipient Name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_name", Required = Newtonsoft.Json.Required.Always)]
        public string Recipient_name { get; set; } = default!;

        /// <summary>
        /// Recipient Phones list
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_phones", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string>? Recipient_phones { get; set; } = default!;

        /// <summary>
        /// Recipient postal code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_postal_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_postal_code { get; set; } = default!;

        /// <summary>
        /// Recipient References list
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_references", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string>? Recipient_references { get; set; } = default!;

        /// <summary>
        /// Recipient town name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_town_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_town_name { get; set; } = default!;

        /// <summary>
        /// Related Shippings
        /// </summary>
        [Newtonsoft.Json.JsonProperty("related_services", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<related_services>? Related_services { get; set; } = default!;

        /// <summary>
        /// Number of backs
        /// </summary>
        [Newtonsoft.Json.JsonProperty("return_count", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? Return_count { get; set; } = default!;

        /// <summary>
        /// Sender address
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Sender_address { get; set; } = default!;

        /// <summary>
        /// Sender country code. Default: Spain (ES). ISO 3166 ALPHA-2 format
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_country_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Sender_country_code { get; set; } = default!;

        /// <summary>
        /// Sender email address for notifications
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_email_notify_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Sender_email_notify_address { get; set; } = default!;

        /// <summary>
        /// Sender name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_name", Required = Newtonsoft.Json.Required.Always)]
        public string Sender_name { get; set; } = default!;

        /// <summary>
        /// Sender phone list
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_phones", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string>? Sender_phones { get; set; } = default!;

        /// <summary>
        /// Sender postal code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_postal_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Sender_postal_code { get; set; } = default!;

        /// <summary>
        /// Sender town name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_town_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Sender_town_name { get; set; } = default!;

        /// <summary>
        /// Shipping code for this manifest used by CTT - Correios de Portugal
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_code", Required = Newtonsoft.Json.Required.Always)]
        public string Shipping_code { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("shipping_code_es", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Shipping_code_es { get; set; } = default!;

        /// <summary>
        /// This field was previously known as `client_date`.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_date", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset Shipping_date { get; set; } = default!;

        /// <summary>
        /// Shipping type code in CTT Correios de Portugal systems
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_type_code", Required = Newtonsoft.Json.Required.Always)]
        public string Shipping_type_code { get; set; } = default!;

        /// <summary>
        /// Shipping type code used in CTT Express systems
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_type_code_es", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Shipping_type_code_es { get; set; } = default!;

        /// <summary>
        /// Approximate total weight of the shipment (in gr)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_weight_declared_gr", Required = Newtonsoft.Json.Required.Always)]
        public double Shipping_weight_declared_gr { get; set; } = default!;

        /// <summary>
        /// Used only in PT. When the customer notifies with this code, the Portuguese system prints documentation for presentation in case of police
        /// </summary>
        [Newtonsoft.Json.JsonProperty("transport_fiscal_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Transport_fiscal_code { get; set; } = default!;

    }

    /// <summary>
    /// An additional service
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class additionals
    {

        /// <summary>
        /// Additional service code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("additional_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Additional_code { get; set; } = default!;

        /// <summary>
        /// Additional service flag
        /// </summary>
        [Newtonsoft.Json.JsonProperty("additional_flag", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? Additional_flag { get; set; } = false;

        /// <summary>
        /// Description of the additional service
        /// </summary>
        [Newtonsoft.Json.JsonProperty("additional_text", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Additional_text { get; set; } = default!;

        /// <summary>
        /// Additional service value
        /// </summary>
        [Newtonsoft.Json.JsonProperty("additional_value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Additional_value { get; set; } = default!;

        /// <summary>
        /// Additional service value unit
        /// </summary>
        [Newtonsoft.Json.JsonProperty("additional_value_unit", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Additional_value_unit { get; set; } = default!;

        /// <summary>
        /// Object postal charge
        /// </summary>
        [Newtonsoft.Json.JsonProperty("cpo", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Cpo { get; set; } = default!;

        /// <summary>
        /// DDA Instructions
        /// </summary>
        [Newtonsoft.Json.JsonProperty("dda_instructions", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Dda_instructions { get; set; } = default!;

        /// <summary>
        /// Code (ID) of the PUDO internally assigned by CTT Express. This code is a combination of the provider code and the point code. This field can be used on ERE and PER additionals
        /// </summary>
        [Newtonsoft.Json.JsonProperty("organic_point_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Organic_point_code { get; set; } = default!;

        /// <summary>
        /// Code (ID) of the PUDO location using the PUDO provider schema. This field can be used on ERE and PER additionals
        /// </summary>
        [Newtonsoft.Json.JsonProperty("point_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Point_code { get; set; } = default!;

        /// <summary>
        /// Human readable name of the PUDO location. This field can be used on ERE and PER additionals
        /// </summary>
        [Newtonsoft.Json.JsonProperty("point_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Point_name { get; set; } = default!;

        /// <summary>
        /// Provider code associated to the PUDO service. This field can be used on ERE and PER additionals
        /// </summary>
        [Newtonsoft.Json.JsonProperty("provider_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Provider_code { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Audit
    {

        /// <summary>
        /// Datetime when the shipping was created
        /// </summary>
        [Newtonsoft.Json.JsonProperty("created_datetime", Required = Newtonsoft.Json.Required.Always)]
        public System.DateTimeOffset Created_datetime { get; set; } = default!;

        /// <summary>
        /// Code of the process that created the manifest
        /// </summary>
        [Newtonsoft.Json.JsonProperty("created_process_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Created_process_code { get; set; } = default!;

        /// <summary>
        /// Creator's user code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("created_user_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Created_user_code { get; set; } = default!;

        /// <summary>
        /// Datetime of the last modification
        /// </summary>
        [Newtonsoft.Json.JsonProperty("modified_datetime", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? Modified_datetime { get; set; } = default!;

        /// <summary>
        /// Code of the process associated with the last modification
        /// </summary>
        [Newtonsoft.Json.JsonProperty("modified_process_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Modified_process_code { get; set; } = default!;

        /// <summary>
        /// Comma separated list of reason codes associated with the last modification done to this shipping
        /// </summary>
        [Newtonsoft.Json.JsonProperty("modified_reason_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Modified_reason_code { get; set; } = default!;

        /// <summary>
        /// User code associated with the last modification
        /// </summary>
        [Newtonsoft.Json.JsonProperty("modified_user_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Modified_user_code { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Delivery
    {

        /// <summary>
        /// Comments about the delivery
        /// </summary>
        [Newtonsoft.Json.JsonProperty("comments", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Comments { get; set; } = "";

        /// <summary>
        /// Contact name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("contact_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Contact_name { get; set; } = "";

        /// <summary>
        /// Latitude coordinate for the delivery
        /// </summary>
        [Newtonsoft.Json.JsonProperty("delivery_latitude_gps", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Delivery_latitude_gps { get; set; } = default!;

        /// <summary>
        /// Longitude coordinate for the delivery
        /// </summary>
        [Newtonsoft.Json.JsonProperty("delivery_longitude_gps", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Delivery_longitude_gps { get; set; } = default!;

        /// <summary>
        /// Referral name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("referral_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Referral_name { get; set; } = "";

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Devolution
    {

        /// <summary>
        /// Devolution address of the devolution action
        /// </summary>
        [Newtonsoft.Json.JsonProperty("devolution_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Devolution_address? Devolution_address { get; set; } = default!;

        /// <summary>
        /// TRL/AGDD, hub code for devolution
        /// </summary>
        [Newtonsoft.Json.JsonProperty("devolution_destin_hub_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Devolution_destin_hub_code { get; set; } = default!;

        /// <summary>
        /// TRL/AGOD, hub code for devolution
        /// </summary>
        [Newtonsoft.Json.JsonProperty("devolution_origin_hub_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Devolution_origin_hub_code { get; set; } = default!;

        /// <summary>
        /// Shipping code of the related devolution shipping service
        /// </summary>
        [Newtonsoft.Json.JsonProperty("devolution_shipping_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Devolution_shipping_code { get; set; } = default!;

    }

    /// <summary>
    /// Represents a shipping item
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class items
    {

        /// <summary>
        /// Code associated with this item on CTT Correios de Portugal
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_code", Required = Newtonsoft.Json.Required.Always)]
        public string Item_code { get; set; } = default!;

        /// <summary>
        /// Use this value if the shipping code to be used is generated by the client, a range of items agreed with CTT Express and a specific logic for generation must be taken into account
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_code_es", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Item_code_es { get; set; } = default!;

        /// <summary>
        /// Item comments
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_comments", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Item_comments { get; set; } = default!;

        /// <summary>
        /// Item height in cm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_height_declared_cm", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Item_height_declared_cm { get; set; } = default!;

        /// <summary>
        /// Item length in cm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_length_declared_cm", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Item_length_declared_cm { get; set; } = default!;

        /// <summary>
        /// Order number
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_order", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Item_order { get; set; } = default!;

        /// <summary>
        /// Item code from the external provider
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_provider_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Item_provider_code { get; set; } = default!;

        /// <summary>
        /// If the label has a barcode other than the one used in CTT Express and an agreement has been reached, this number must be indicated so that it can be read by the Sorters.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_synonym_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Item_synonym_code { get; set; } = default!;

        /// <summary>
        /// Item weight in gr
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_volumetric_weight_gr", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Item_volumetric_weight_gr { get; set; } = default!;

        /// <summary>
        /// Item weight in gr
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_weight_declared_gr", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Item_weight_declared_gr { get; set; } = default!;

        /// <summary>
        /// Item width in cm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_width_declared_cm", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Item_width_declared_cm { get; set; } = default!;

    }

    /// <summary>
    /// Represents a Related Shippings item
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class related_services
    {

        /// <summary>
        /// Relation type
        /// </summary>
        [Newtonsoft.Json.JsonProperty("relation_type", Required = Newtonsoft.Json.Required.Always)]
        public string Relation_type { get; set; } = default!;

        /// <summary>
        /// Shipping Code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_code", Required = Newtonsoft.Json.Required.Always)]
        public string Shipping_code { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Devolution_address
    {

        /// <summary>
        /// Address information
        /// </summary>
        [Newtonsoft.Json.JsonProperty("address", Required = Newtonsoft.Json.Required.Always)]
        public string Address { get; set; } = default!;

        /// <summary>
        /// Country code ISO Alpha 2
        /// </summary>
        [Newtonsoft.Json.JsonProperty("country_code", Required = Newtonsoft.Json.Required.Always)]
        public string Country_code { get; set; } = default!;

        /// <summary>
        /// Name of the recipient of the devolution
        /// </summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Devolution notification emails
        /// </summary>
        [Newtonsoft.Json.JsonProperty("notification_emails", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string>? Notification_emails { get; set; } = default!;

        /// <summary>
        /// Devolution phone list
        /// </summary>
        [Newtonsoft.Json.JsonProperty("phones", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string>? Phones { get; set; } = default!;

        /// <summary>
        /// Postal code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("postal_code", Required = Newtonsoft.Json.Required.Always)]
        public string Postal_code { get; set; } = default!;

        /// <summary>
        /// Town name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("town_name", Required = Newtonsoft.Json.Required.Always)]
        public string Town_name { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    internal class DateFormatConverter : Newtonsoft.Json.Converters.IsoDateTimeConverter
    {
        public DateFormatConverter()
        {
            DateTimeFormat = "yyyy-MM-dd";
        }
    }
}