// ------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Kafka JSON Schema.
//     Root schema title: EopItemTrackingShippingMailV1Value
//     This file is intended for use with Confluent.SchemaRegistry.Serdes.Json.
// </auto-generated>
// ------------------------------------------------------------------------------
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace Tester.Models.EopItemTrackingShippingMailV1
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [Newtonsoft.Json.JsonObject(Title = "EopItemTrackingShippingMailV1Value")]
    public partial class EopItemTrackingShippingMailV1Value
    {

        [Newtonsoft.Json.JsonProperty("metadata", Required = Newtonsoft.Json.Required.Always)]
        public Metadata Metadata { get; set; } = new Metadata();

        [Newtonsoft.Json.JsonProperty("shipping", Required = Newtonsoft.Json.Required.Always)]
        public Shipping Shipping { get; set; } = new Shipping();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Metadata
    {

        [Newtonsoft.Json.JsonProperty("correlation_id", Required = Newtonsoft.Json.Required.Always)]
        public string Correlation_id { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("data_type", Required = Newtonsoft.Json.Required.Always)]
        public string Data_type { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("interchange_id", Required = Newtonsoft.Json.Required.Always)]
        public string Interchange_id { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("source", Required = Newtonsoft.Json.Required.Always)]
        public string Source { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("timestamp", Required = Newtonsoft.Json.Required.Always)]
        public System.DateTimeOffset Timestamp { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Shipping
    {

        [Newtonsoft.Json.JsonProperty("additionals", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<additionals>? Additionals { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("customs_info", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Customs_info? Customs_info { get; set; } = default!;

        /// <summary>
        /// format
        /// </summary>
        [Newtonsoft.Json.JsonProperty("format", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Format { get; set; } = default!;

        /// <summary>
        /// Shipping item list
        /// </summary>
        [Newtonsoft.Json.JsonProperty("items", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<items>? Items { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("recipient", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Recipient? Recipient { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sender", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Sender? Sender { get; set; } = default!;

        /// <summary>
        /// shipping code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_code", Required = Newtonsoft.Json.Required.Always)]
        public string Shipping_code { get; set; } = default!;

        /// <summary>
        /// shipping type code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_type_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Shipping_type_code { get; set; } = default!;

        /// <summary>
        /// shipping weight declared gr
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_weight_declared", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Shipping_weight_declared { get; set; } = default!;

        /// <summary>
        /// Tax zone
        /// </summary>
        [Newtonsoft.Json.JsonProperty("tax_zone", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Tax_zone { get; set; } = default!;

        /// <summary>
        /// Velocity
        /// </summary>
        [Newtonsoft.Json.JsonProperty("velocity", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Velocity { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class additionals
    {

        [Newtonsoft.Json.JsonProperty("additional_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Additional_code { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("additional_value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Additional_value { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Customs_info
    {

        [Newtonsoft.Json.JsonProperty("associated_document", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Associated_document? Associated_document { get; set; } = default!;

        /// <summary>
        /// Sender's name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("company_name", Required = Newtonsoft.Json.Required.Always)]
        public string Company_name { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("content_piece", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<content_piece> Content_piece { get; set; } = new System.Collections.ObjectModel.Collection<content_piece>();

        /// <summary>
        /// Weight of the item in kg, as declared by the mailer
        /// </summary>
        [Newtonsoft.Json.JsonProperty("declared_gross_weigth_kg", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Declared_gross_weigth_kg { get; set; } = default!;

        /// <summary>
        /// The ANSI 2 character code for the country the item is being sent to, as defined by ISO3066
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destination_country_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Destination_country_code { get; set; } = default!;

        /// <summary>
        /// Postal Operator Code of the inbound/destination Postal Operator, as defined in UPU Code list 118 Party identifiers
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destination_postal_operator", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Destination_postal_operator { get; set; } = default!;

        /// <summary>
        /// Human readable identifier of the e-Retailer as a PDDP Member. Unique e-Retailer ID as provided by IPC on setup
        /// </summary>
        [Newtonsoft.Json.JsonProperty("eretailer_identifier", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Eretailer_identifier { get; set; } = default!;

        /// <summary>
        /// Name of the LCC Provider. Please use UNKNOWN if e-retailer didnt specify their LCC provider
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcc_provider_description", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Lcc_provider_description { get; set; } = default!;

        /// <summary>
        /// Human readable identifier of the LCC Provider. Please use UNKNOWN if e-retailer didn t specify their LCC provider
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcc_provider_identifier", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Lcc_provider_identifier { get; set; } = default!;

        /// <summary>
        /// The default value 11 for Sale of Goods as per UPU code list 136, the value for indication for customs of the type of contract under which the item is mailed, will be provided in this field
        /// </summary>
        [Newtonsoft.Json.JsonProperty("nature_of_transaction_code", Required = Newtonsoft.Json.Required.Always)]
        public string Nature_of_transaction_code { get; set; } = default!;

        /// <summary>
        /// Ancillary information related to customs processing of the item, expressed as a free text value.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("observations", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Observations { get; set; } = default!;

        /// <summary>
        /// Postal Operator Code of the outbound/origin Postal Operator, as defined in UPU Code list 118 Party identifiers
        /// </summary>
        [Newtonsoft.Json.JsonProperty("origin_postal_operator", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Origin_postal_operator { get; set; } = default!;

        /// <summary>
        /// Name of the Payment Provider. Please use UNKNOWN if e-retailer didn t specify their payment platform provider
        /// </summary>
        [Newtonsoft.Json.JsonProperty("payment_provider_description", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Payment_provider_description { get; set; } = default!;

        /// <summary>
        /// Human readable identifier of the Payment Provider. Please use UNKNOWN if e-retailer didn t specify the product code used by their LCC provider
        /// </summary>
        [Newtonsoft.Json.JsonProperty("payment_provider_identifier", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Payment_provider_identifier { get; set; } = default!;

        /// <summary>
        /// Addressee s street address
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_address { get; set; } = default!;

        /// <summary>
        /// Addressee s country. The ANSI 2-character code for the country the item is being sent to, as defined by ISO3066
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_country_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_country_code { get; set; } = default!;

        /// <summary>
        /// Addressee s email address
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_email", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_email { get; set; } = default!;

        /// <summary>
        /// Fax number of the recipient, corresponding to addressee
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_fax", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_fax { get; set; } = default!;

        /// <summary>
        /// Full name of the addressee
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_name", Required = Newtonsoft.Json.Required.Always)]
        public string Recipient_name { get; set; } = default!;

        /// <summary>
        /// Addressee s phone number
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_phone", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_phone { get; set; } = default!;

        /// <summary>
        /// Recipient postal code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_postal_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_postal_code { get; set; } = default!;

        /// <summary>
        /// Addressee s National ID Number if applicable
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_ref", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_ref { get; set; } = default!;

        /// <summary>
        /// Addressee s city
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_town", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_town { get; set; } = default!;

        /// <summary>
        /// Sender s street name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipper_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Shipper_address { get; set; } = default!;

        /// <summary>
        /// The ANSI 2 character code for the country the item is being sent from, as defined by ISO3066
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipper_country_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Shipper_country_code { get; set; } = default!;

        /// <summary>
        /// Sender s email address
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipper_email", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Shipper_email { get; set; } = default!;

        /// <summary>
        /// Sender s phone number
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipper_phone", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Shipper_phone { get; set; } = default!;

        /// <summary>
        /// Sender s postcode
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipper_postal_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Shipper_postal_code { get; set; } = default!;

        /// <summary>
        /// Sender s city
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipper_town", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Shipper_town { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("shopping_cart", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Shopping_cart? Shopping_cart { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Represents a shipping item
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class items
    {

        /// <summary>
        /// Item code 
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_code", Required = Newtonsoft.Json.Required.Always)]
        public string Item_code { get; set; } = default!;

        /// <summary>
        /// Item height declared cm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_height_declared", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Item_height_declared { get; set; } = default!;

        /// <summary>
        /// Item length declared cm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_length_declared", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Item_length_declared { get; set; } = default!;

        /// <summary>
        /// Item weight declared gr
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_weight_declared", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Item_weight_declared { get; set; } = default!;

        /// <summary>
        /// Item width declared cm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_width_declared", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Item_width_declared { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Recipient
    {

        /// <summary>
        /// Address
        /// </summary>
        [Newtonsoft.Json.JsonProperty("address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Address { get; set; } = default!;

        /// <summary>
        /// Contact
        /// </summary>
        [Newtonsoft.Json.JsonProperty("contact", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Contact { get; set; } = default!;

        /// <summary>
        /// Country code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("country_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Country_code { get; set; } = default!;

        /// <summary>
        /// Email notify address
        /// </summary>
        [Newtonsoft.Json.JsonProperty("email_notify_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Email_notify_address { get; set; } = default!;

        /// <summary>
        /// Name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Name { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("phones", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string>? Phones { get; set; } = default!;

        /// <summary>
        /// Postal code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("postal_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Postal_code { get; set; } = default!;

        /// <summary>
        /// Postal code description
        /// </summary>
        [Newtonsoft.Json.JsonProperty("postal_code_desc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Postal_code_desc { get; set; } = default!;

        /// <summary>
        /// Tax identification number
        /// </summary>
        [Newtonsoft.Json.JsonProperty("tax_identification_number", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Tax_identification_number { get; set; } = default!;

        /// <summary>
        /// Town name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("town_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Town_name { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Sender
    {

        /// <summary>
        /// Address
        /// </summary>
        [Newtonsoft.Json.JsonProperty("address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Address { get; set; } = default!;

        /// <summary>
        /// Client Reference
        /// </summary>
        [Newtonsoft.Json.JsonProperty("client_ref", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Client_ref { get; set; } = default!;

        /// <summary>
        /// Contact
        /// </summary>
        [Newtonsoft.Json.JsonProperty("contact", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Contact { get; set; } = default!;

        /// <summary>
        /// Country code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("country_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Country_code { get; set; } = default!;

        /// <summary>
        /// Document Key
        /// </summary>
        [Newtonsoft.Json.JsonProperty("document_key", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Document_key { get; set; } = default!;

        /// <summary>
        /// Email notify address
        /// </summary>
        [Newtonsoft.Json.JsonProperty("email_notify_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Email_notify_address { get; set; } = default!;

        /// <summary>
        /// Name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Name { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("phones", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string>? Phones { get; set; } = default!;

        /// <summary>
        /// Postal code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("postal_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Postal_code { get; set; } = default!;

        /// <summary>
        /// Postal code description
        /// </summary>
        [Newtonsoft.Json.JsonProperty("postal_code_desc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Postal_code_desc { get; set; } = default!;

        /// <summary>
        /// Recipient key
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_key", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Recipient_key { get; set; } = default!;

        /// <summary>
        /// Tax identification number
        /// </summary>
        [Newtonsoft.Json.JsonProperty("tax_identification_number", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Tax_identification_number { get; set; } = default!;

        /// <summary>
        /// Town name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("town_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Town_name { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Associated_document
    {

        /// <summary>
        /// Type of the associated document that accompanies
        /// </summary>
        [Newtonsoft.Json.JsonProperty("doc_type", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Doc_type { get; set; } = default!;

        /// <summary>
        /// Reference or identifier of the document that accompanies
        /// </summary>
        [Newtonsoft.Json.JsonProperty("identifier", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Identifier { get; set; } = default!;

        /// <summary>
        /// Name or description of the document that accompanies
        /// </summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Name { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class content_piece
    {

        /// <summary>
        /// The unique product ID assigned by the LCC provider. Please use “UNKNOWN” if e-retailer didn’t specify the product code used by their LCC provider.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcc_provider_product_identifier", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Lcc_provider_product_identifier { get; set; } = default!;

        /// <summary>
        /// The NET weight of items being shipped. This is important for certain countries. The weight should be in kilograms
        /// </summary>
        [Newtonsoft.Json.JsonProperty("net_weight_kg", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Net_weight_kg { get; set; } = default!;

        /// <summary>
        /// ISO 3166–1 country code of the location in which the content piece was produced or manufactured
        /// </summary>
        [Newtonsoft.Json.JsonProperty("origin_country_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Origin_country_code { get; set; } = default!;

        /// <summary>
        /// Product description provided by the e-Retailer (from their product catalogue)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("product_description", Required = Newtonsoft.Json.Required.Always)]
        public string Product_description { get; set; } = default!;

        /// <summary>
        /// The percentage duty rate for the product in the destination. If not applicable or unknown, please provide “0”
        /// </summary>
        [Newtonsoft.Json.JsonProperty("product_duty_rate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Product_duty_rate { get; set; } = default!;

        /// <summary>
        /// The value of the duty payable on the product
        /// </summary>
        [Newtonsoft.Json.JsonProperty("product_duty_value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Product_duty_value { get; set; } = default!;

        /// <summary>
        /// The percentage tax rate for the product in the destination country. If unknown, please provide “0”
        /// </summary>
        [Newtonsoft.Json.JsonProperty("product_tax_rate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Product_tax_rate { get; set; } = default!;

        /// <summary>
        /// The value of the tax payable on the product
        /// </summary>
        [Newtonsoft.Json.JsonProperty("product_tax_value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Product_tax_value { get; set; } = default!;

        /// <summary>
        /// The total cost of the product including duty and taxes
        /// </summary>
        [Newtonsoft.Json.JsonProperty("product_total", Required = Newtonsoft.Json.Required.Always)]
        public double Product_total { get; set; } = default!;

        /// <summary>
        /// Currency of the declared total value for the content piece
        /// </summary>
        [Newtonsoft.Json.JsonProperty("product_total_currency", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Product_total_currency { get; set; } = default!;

        /// <summary>
        /// The unit price of the product being calculated, without a currency symbol, in the local currency of the destination country
        /// </summary>
        [Newtonsoft.Json.JsonProperty("product_value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Product_value { get; set; } = default!;

        /// <summary>
        /// Sequence number of the product (content piece) within the set of products associated with the item
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sequence_number", Required = Newtonsoft.Json.Required.Always)]
        public int Sequence_number { get; set; } = default!;

        /// <summary>
        /// The Harmonized Systems (HS) code used to define the product. It can be 6, 8 or 10 digits. Specific countries may require one of those standards (eg Irish Customs requires 10 digits)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("tariff_code", Required = Newtonsoft.Json.Required.Always)]
        public string Tariff_code { get; set; } = default!;

        /// <summary>
        /// Units
        /// </summary>
        [Newtonsoft.Json.JsonProperty("units", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? Units { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Shopping_cart
    {

        /// <summary>
        /// Without a currency symbol, in the local currency of the destination country
        /// </summary>
        [Newtonsoft.Json.JsonProperty("cost", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Cost { get; set; } = default!;

        /// <summary>
        /// The ANSI 3 character code of the Destination Country Currency
        /// </summary>
        [Newtonsoft.Json.JsonProperty("currency", Required = Newtonsoft.Json.Required.Always)]
        public string Currency { get; set; } = default!;

        /// <summary>
        /// The ANSI 3 character code for the preferred currency of the Destination Country
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destination_country_currency", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Destination_country_currency { get; set; } = default!;

        /// <summary>
        /// The value for Duty deminimis
        /// </summary>
        [Newtonsoft.Json.JsonProperty("duty_deminimis_value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Duty_deminimis_value { get; set; } = default!;

        /// <summary>
        /// The total of all products submitted with the shipping cost, duty and tax applied. This is a subtotal that contains all costs except surcharges
        /// </summary>
        [Newtonsoft.Json.JsonProperty("flc_total_cost_no_surcharge", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Flc_total_cost_no_surcharge { get; set; } = default!;

        /// <summary>
        /// Amount of the item’s insured value
        /// </summary>
        [Newtonsoft.Json.JsonProperty("insured_value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Insured_value { get; set; } = default!;

        /// <summary>
        /// Admin Fee charged by the Destination Post (in the currency of the Destination Country). If unknown, please provide “0”
        /// </summary>
        [Newtonsoft.Json.JsonProperty("surcharge_value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Surcharge_value { get; set; } = default!;

        /// <summary>
        /// The value for Tax deminimis
        /// </summary>
        [Newtonsoft.Json.JsonProperty("tax_deminimis_value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Tax_deminimis_value { get; set; } = default!;

        /// <summary>
        /// Total of all products submitted with the shipping cost, duty, tax, surcharge and insurance
        /// </summary>
        [Newtonsoft.Json.JsonProperty("total_cost", Required = Newtonsoft.Json.Required.Always)]
        public double Total_cost { get; set; } = default!;

        /// <summary>
        /// The total duty payable on all items being shipped
        /// </summary>
        [Newtonsoft.Json.JsonProperty("total_duty", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Total_duty { get; set; } = default!;

        /// <summary>
        /// The total tax payable on all items being shipped
        /// </summary>
        [Newtonsoft.Json.JsonProperty("total_tax", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Total_tax { get; set; } = default!;

        /// <summary>
        /// Admin Fee charged by the Destination Post (in the currency of the Destination Country). If unknown, please provide “0”
        /// </summary>
        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.Always)]
        public double Value { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }
}