// ------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Kafka AVRO Schema.
//     Root schema title: OrderV1Value
//     This file is intended for use with Confluent.SchemaRegistry.Serdes.Avro.
// </auto-generated>
// ------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tester.Models.OrderV1
{
  using System;
  using System.Collections.Generic;
  using System.Text;
  using global::Avro;
  using global::Avro.Specific;
  
  
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ModelGenerator", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
  public partial class OrderV1Value : global::Avro.Specific.ISpecificRecord
  {
    
    public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""OrderV1Value"",""namespace"":""Tester.Models.OrderV1"",""fields"":[{""name"":""orderId"",""type"":""string""},{""name"":""customerId"",""type"":""string""},{""name"":""amount"",""type"":""double""},{""name"":""currency"",""default"":null,""type"":[""null"",""string""]},{""name"":""createdAt"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
    
    private string _orderId;
    
    private string _customerId;
    
    private double _amount;
    
    private string _currency;
    
    private System.DateTime _createdAt;
    
    public virtual global::Avro.Schema Schema
    {
      get
      {
        return OrderV1Value._SCHEMA;
      }
    }
    
    public string orderId
    {
      get
      {
        return this._orderId;
      }
      set
      {
        this._orderId = value;
      }
    }
    
    public string customerId
    {
      get
      {
        return this._customerId;
      }
      set
      {
        this._customerId = value;
      }
    }
    
    public double amount
    {
      get
      {
        return this._amount;
      }
      set
      {
        this._amount = value;
      }
    }
    
    public string currency
    {
      get
      {
        return this._currency;
      }
      set
      {
        this._currency = value;
      }
    }
    
    public System.DateTime createdAt
    {
      get
      {
        return this._createdAt;
      }
      set
      {
        this._createdAt = value;
      }
    }
    
    public virtual object Get(int fieldPos)
    {
      switch (fieldPos)
			{
			case 0: return this.orderId;
			case 1: return this.customerId;
			case 2: return this.amount;
			case 3: return this.currency;
			case 4: return this.createdAt;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
    }
    
    public virtual void Put(int fieldPos, object fieldValue)
    {
      switch (fieldPos)
			{
			case 0: this.orderId = (System.String)fieldValue; break;
			case 1: this.customerId = (System.String)fieldValue; break;
			case 2: this.amount = (System.Double)fieldValue; break;
			case 3: this.currency = (System.String)fieldValue; break;
			case 4: this.createdAt = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
    }
  }
}
