// ------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Kafka AVRO Schema.
//     Root schema title: PaymentV1Key
//     This file is intended for use with Confluent.SchemaRegistry.Serdes.Avro.
// </auto-generated>
// ------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tester.Models.PaymentV1
{
  using System;
  using System.Collections.Generic;
  using System.Text;
  using global::Avro;
  using global::Avro.Specific;
  
  
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ModelGenerator", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
  public partial class PaymentV1Key : global::Avro.Specific.ISpecificRecord
  {
    
    public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""PaymentV1Key"",""namespace"":""Tester.Models.PaymentV1"",""fields"":[{""name"":""paymentId"",""type"":""string""},{""name"":""sourceSystem"",""type"":{""type"":""enum"",""name"":""SourceSystem"",""namespace"":""Tester.Models.PaymentV1"",""symbols"":[""WEB"",""MOBILE"",""POS""]}},{""name"":""region"",""default"":null,""type"":[""null"",""string""]}]}");
    
    private string _paymentId;
    
    private Tester.Models.PaymentV1.SourceSystem _sourceSystem;
    
    private string _region;
    
    public virtual global::Avro.Schema Schema
    {
      get
      {
        return PaymentV1Key._SCHEMA;
      }
    }
    
    public string paymentId
    {
      get
      {
        return this._paymentId;
      }
      set
      {
        this._paymentId = value;
      }
    }
    
    public Tester.Models.PaymentV1.SourceSystem sourceSystem
    {
      get
      {
        return this._sourceSystem;
      }
      set
      {
        this._sourceSystem = value;
      }
    }
    
    public string region
    {
      get
      {
        return this._region;
      }
      set
      {
        this._region = value;
      }
    }
    
    public virtual object Get(int fieldPos)
    {
      switch (fieldPos)
			{
			case 0: return this.paymentId;
			case 1: return this.sourceSystem;
			case 2: return this.region;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
    }
    
    public virtual void Put(int fieldPos, object fieldValue)
    {
      switch (fieldPos)
			{
			case 0: this.paymentId = (System.String)fieldValue; break;
			case 1: this.sourceSystem = (Tester.Models.PaymentV1.SourceSystem)fieldValue; break;
			case 2: this.region = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
    }
  }
  
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ModelGenerator", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
  public enum SourceSystem
  {
    
    WEB,
    
    MOBILE,
    
    POS,
  }
}
