// ------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Kafka AVRO Schema.
//     Root schema title: PaymentV1Value
//     This file is intended for use with Confluent.SchemaRegistry.Serdes.Avro.
// </auto-generated>
// ------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tester.Models.PaymentV1
{
  using System;
  using System.Collections.Generic;
  using System.Text;
  using global::Avro;
  using global::Avro.Specific;
  
  
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ModelGenerator", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
  public partial class PaymentV1Value : global::Avro.Specific.ISpecificRecord
  {
    
    public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""PaymentV1Value"",""namespace"":""Tester.Models.PaymentV1"",""fields"":[{""name"":""paymentId"",""type"":""string""},{""name"":""status"",""type"":{""type"":""enum"",""name"":""PaymentStatus"",""namespace"":""Tester.Models.PaymentV1"",""symbols"":[""PENDING"",""COMPLETED"",""FAILED""]}},{""name"":""amount"",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":10,""scale"":2}},{""name"":""processedAt"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}},{""name"":""metadata"",""type"":{""type"":""map"",""values"":""string""}},{""name"":""failureReason"",""default"":null,""type"":[""null"",""string""]},{""name"":""paymentMethod"",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""CardDetails"",""namespace"":""Tester.Models.PaymentV1"",""fields"":[{""name"":""last4"",""type"":""string""},{""name"":""brand"",""type"":""string""}]}]}]}");
    
    private string _paymentId;
    
    private Tester.Models.PaymentV1.PaymentStatus _status;
    
    private Avro.AvroDecimal _amount;
    
    private System.DateTime _processedAt;
    
    private IDictionary<string,System.String> _metadata;
    
    private string _failureReason;
    
    private Tester.Models.PaymentV1.CardDetails _paymentMethod;
    
    public virtual global::Avro.Schema Schema
    {
      get
      {
        return PaymentV1Value._SCHEMA;
      }
    }
    
    public string paymentId
    {
      get
      {
        return this._paymentId;
      }
      set
      {
        this._paymentId = value;
      }
    }
    
    public Tester.Models.PaymentV1.PaymentStatus status
    {
      get
      {
        return this._status;
      }
      set
      {
        this._status = value;
      }
    }
    
    public Avro.AvroDecimal amount
    {
      get
      {
        return this._amount;
      }
      set
      {
        this._amount = value;
      }
    }
    
    public System.DateTime processedAt
    {
      get
      {
        return this._processedAt;
      }
      set
      {
        this._processedAt = value;
      }
    }
    
    public IDictionary<string,System.String> metadata
    {
      get
      {
        return this._metadata;
      }
      set
      {
        this._metadata = value;
      }
    }
    
    public string failureReason
    {
      get
      {
        return this._failureReason;
      }
      set
      {
        this._failureReason = value;
      }
    }
    
    public Tester.Models.PaymentV1.CardDetails paymentMethod
    {
      get
      {
        return this._paymentMethod;
      }
      set
      {
        this._paymentMethod = value;
      }
    }
    
    public virtual object Get(int fieldPos)
    {
      switch (fieldPos)
			{
			case 0: return this.paymentId;
			case 1: return this.status;
			case 2: return this.amount;
			case 3: return this.processedAt;
			case 4: return this.metadata;
			case 5: return this.failureReason;
			case 6: return this.paymentMethod;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
    }
    
    public virtual void Put(int fieldPos, object fieldValue)
    {
      switch (fieldPos)
			{
			case 0: this.paymentId = (System.String)fieldValue; break;
			case 1: this.status = (Tester.Models.PaymentV1.PaymentStatus)fieldValue; break;
			case 2: this.amount = (Avro.AvroDecimal)fieldValue; break;
			case 3: this.processedAt = (System.DateTime)fieldValue; break;
			case 4: this.metadata = (IDictionary<string,System.String>)fieldValue; break;
			case 5: this.failureReason = (System.String)fieldValue; break;
			case 6: this.paymentMethod = (Tester.Models.PaymentV1.CardDetails)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
    }
  }
  
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ModelGenerator", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
  public enum PaymentStatus
  {
    
    PENDING,
    
    COMPLETED,
    
    FAILED,
  }
  
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ModelGenerator", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
  public partial class CardDetails : global::Avro.Specific.ISpecificRecord
  {
    
    public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(("{\"type\":\"record\",\"name\":\"CardDetails\",\"namespace\":\"Tester.Models.PaymentV1\",\"fiel" +
        "ds\":[{\"name\":\"last4\",\"type\":\"string\"},{\"name\":\"brand\",\"type\":\"string\"}]}"));
    
    private string _last4;
    
    private string _brand;
    
    public virtual global::Avro.Schema Schema
    {
      get
      {
        return CardDetails._SCHEMA;
      }
    }
    
    public string last4
    {
      get
      {
        return this._last4;
      }
      set
      {
        this._last4 = value;
      }
    }
    
    public string brand
    {
      get
      {
        return this._brand;
      }
      set
      {
        this._brand = value;
      }
    }
    
    public virtual object Get(int fieldPos)
    {
      switch (fieldPos)
			{
			case 0: return this.last4;
			case 1: return this.brand;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
    }
    
    public virtual void Put(int fieldPos, object fieldValue)
    {
      switch (fieldPos)
			{
			case 0: this.last4 = (System.String)fieldValue; break;
			case 1: this.brand = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
    }
  }
}
