// ------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Kafka AVRO Schema.
//     Root schema title: ShipmentV1Key
//     This file is intended for use with Confluent.SchemaRegistry.Serdes.Avro.
// </auto-generated>
// ------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tester.Models.ShipmentV1
{
  using System;
  using System.Collections.Generic;
  using System.Text;
  using global::Avro;
  using global::Avro.Specific;
  
  
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ModelGenerator", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
  public partial class ShipmentV1Key : global::Avro.Specific.ISpecificRecord
  {
    
    public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(("{\"type\":\"record\",\"name\":\"ShipmentV1Key\",\"namespace\":\"Tester.Models.ShipmentV1\",\"f" +
        "ields\":[{\"name\":\"shipmentId\",\"type\":\"string\"},{\"name\":\"tenantId\",\"type\":\"string\"" +
        "}]}"));
    
    private string _shipmentId;
    
    private string _tenantId;
    
    public virtual global::Avro.Schema Schema
    {
      get
      {
        return ShipmentV1Key._SCHEMA;
      }
    }
    
    public string shipmentId
    {
      get
      {
        return this._shipmentId;
      }
      set
      {
        this._shipmentId = value;
      }
    }
    
    public string tenantId
    {
      get
      {
        return this._tenantId;
      }
      set
      {
        this._tenantId = value;
      }
    }
    
    public virtual object Get(int fieldPos)
    {
      switch (fieldPos)
			{
			case 0: return this.shipmentId;
			case 1: return this.tenantId;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
    }
    
    public virtual void Put(int fieldPos, object fieldValue)
    {
      switch (fieldPos)
			{
			case 0: this.shipmentId = (System.String)fieldValue; break;
			case 1: this.tenantId = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
    }
  }
}
