// ------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Kafka AVRO Schema.
//     Root schema title: ShipmentV1Value
//     This file is intended for use with Confluent.SchemaRegistry.Serdes.Avro.
// </auto-generated>
// ------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tester.Models.ShipmentV1
{
  using System;
  using System.Collections.Generic;
  using System.Text;
  using global::Avro;
  using global::Avro.Specific;
  
  
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ModelGenerator", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
  public partial class ShipmentV1Value : global::Avro.Specific.ISpecificRecord
  {
    
    public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ShipmentV1Value"",""namespace"":""Tester.Models.ShipmentV1"",""fields"":[{""name"":""shipmentId"",""type"":""string""},{""name"":""status"",""type"":{""type"":""enum"",""name"":""ShipmentStatus"",""namespace"":""Tester.Models.ShipmentV1"",""symbols"":[""CREATED"",""IN_TRANSIT"",""DELIVERED"",""FAILED""]}},{""name"":""items"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""ShipmentItem"",""namespace"":""Tester.Models.ShipmentV1"",""fields"":[{""name"":""sku"",""type"":""string""},{""name"":""quantity"",""type"":""int""}]}}},{""name"":""destination"",""type"":{""type"":""record"",""name"":""Address"",""namespace"":""Tester.Models.ShipmentV1"",""fields"":[{""name"":""street"",""type"":""string""},{""name"":""city"",""type"":""string""},{""name"":""postalCode"",""type"":""string""},{""name"":""country"",""type"":""string""}]}}]}");
    
    private string _shipmentId;
    
    private Tester.Models.ShipmentV1.ShipmentStatus _status;
    
    private IList<Tester.Models.ShipmentV1.ShipmentItem> _items;
    
    private Tester.Models.ShipmentV1.Address _destination;
    
    public virtual global::Avro.Schema Schema
    {
      get
      {
        return ShipmentV1Value._SCHEMA;
      }
    }
    
    public string shipmentId
    {
      get
      {
        return this._shipmentId;
      }
      set
      {
        this._shipmentId = value;
      }
    }
    
    public Tester.Models.ShipmentV1.ShipmentStatus status
    {
      get
      {
        return this._status;
      }
      set
      {
        this._status = value;
      }
    }
    
    public IList<Tester.Models.ShipmentV1.ShipmentItem> items
    {
      get
      {
        return this._items;
      }
      set
      {
        this._items = value;
      }
    }
    
    public Tester.Models.ShipmentV1.Address destination
    {
      get
      {
        return this._destination;
      }
      set
      {
        this._destination = value;
      }
    }
    
    public virtual object Get(int fieldPos)
    {
      switch (fieldPos)
			{
			case 0: return this.shipmentId;
			case 1: return this.status;
			case 2: return this.items;
			case 3: return this.destination;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
    }
    
    public virtual void Put(int fieldPos, object fieldValue)
    {
      switch (fieldPos)
			{
			case 0: this.shipmentId = (System.String)fieldValue; break;
			case 1: this.status = (Tester.Models.ShipmentV1.ShipmentStatus)fieldValue; break;
			case 2: this.items = (IList<Tester.Models.ShipmentV1.ShipmentItem>)fieldValue; break;
			case 3: this.destination = (Tester.Models.ShipmentV1.Address)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
    }
  }
  
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ModelGenerator", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
  public enum ShipmentStatus
  {
    
    CREATED,
    
    IN_TRANSIT,
    
    DELIVERED,
    
    FAILED,
  }
  
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ModelGenerator", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
  public partial class ShipmentItem : global::Avro.Specific.ISpecificRecord
  {
    
    public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(("{\"type\":\"record\",\"name\":\"ShipmentItem\",\"namespace\":\"Tester.Models.ShipmentV1\",\"fi" +
        "elds\":[{\"name\":\"sku\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"int\"}]}"));
    
    private string _sku;
    
    private int _quantity;
    
    public virtual global::Avro.Schema Schema
    {
      get
      {
        return ShipmentItem._SCHEMA;
      }
    }
    
    public string sku
    {
      get
      {
        return this._sku;
      }
      set
      {
        this._sku = value;
      }
    }
    
    public int quantity
    {
      get
      {
        return this._quantity;
      }
      set
      {
        this._quantity = value;
      }
    }
    
    public virtual object Get(int fieldPos)
    {
      switch (fieldPos)
			{
			case 0: return this.sku;
			case 1: return this.quantity;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
    }
    
    public virtual void Put(int fieldPos, object fieldValue)
    {
      switch (fieldPos)
			{
			case 0: this.sku = (System.String)fieldValue; break;
			case 1: this.quantity = (System.Int32)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
    }
  }
  
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ModelGenerator", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
  public partial class Address : global::Avro.Specific.ISpecificRecord
  {
    
    public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(("{\"type\":\"record\",\"name\":\"Address\",\"namespace\":\"Tester.Models.ShipmentV1\",\"fields\"" +
        ":[{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"pos" +
        "talCode\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"}]}"));
    
    private string _street;
    
    private string _city;
    
    private string _postalCode;
    
    private string _country;
    
    public virtual global::Avro.Schema Schema
    {
      get
      {
        return Address._SCHEMA;
      }
    }
    
    public string street
    {
      get
      {
        return this._street;
      }
      set
      {
        this._street = value;
      }
    }
    
    public string city
    {
      get
      {
        return this._city;
      }
      set
      {
        this._city = value;
      }
    }
    
    public string postalCode
    {
      get
      {
        return this._postalCode;
      }
      set
      {
        this._postalCode = value;
      }
    }
    
    public string country
    {
      get
      {
        return this._country;
      }
      set
      {
        this._country = value;
      }
    }
    
    public virtual object Get(int fieldPos)
    {
      switch (fieldPos)
			{
			case 0: return this.street;
			case 1: return this.city;
			case 2: return this.postalCode;
			case 3: return this.country;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
    }
    
    public virtual void Put(int fieldPos, object fieldValue)
    {
      switch (fieldPos)
			{
			case 0: this.street = (System.String)fieldValue; break;
			case 1: this.city = (System.String)fieldValue; break;
			case 2: this.postalCode = (System.String)fieldValue; break;
			case 3: this.country = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
    }
  }
}
