using System.Text.RegularExpressions;
using ModelGenerator.Types;

namespace ModelGenerator.Utils;

public static class Models
{
  public static string AddHeader(string code, SchemaTypes schemaType, string schemaTitle)
  {
    var header = $$"""
// ------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Kafka {{schemaType}} Schema.
//     Root schema title: {{schemaTitle}}
//     This file is intended for use with Confluent.SchemaRegistry.Serdes.Json.
// </auto-generated>
// ------------------------------------------------------------------------------

""";

    return header + code;
  }

  public static string EnsureRootJsonObjectTitle(string code, string schemaTitle)
  {
    var pattern = @"(?m)^(\s*)(public\s+(?:partial\s+)?class\s+\w+)";
    var replacement = $"$1[Newtonsoft.Json.JsonObject(Title = \"{EscapeCSharpString(schemaTitle)}\")]{Environment.NewLine}$1$2";

    var regex = new Regex(pattern);
    return regex.Replace(code, replacement, 1);
  }

  public static string EnsurePartialClasses(string code)
  {
    return Regex.Replace(
      code,
      @"(?m)^(\s*public\s+)(class\s+)",
      "$1partial $2"
    );
  }

  public static string ToPascalCaseIdentifier(string value)
  {
    if (string.IsNullOrWhiteSpace(value))
    {
      return "KafkaMessage";
    }

    var parts = Regex.Split(value, @"[^A-Za-z0-9_]+")
      .Where(x => string.IsNullOrWhiteSpace(x) == false)
      .Select(x =>
      {
        var cleaned = Regex.Replace(x, @"[^A-Za-z0-9_]", "");
        if (string.IsNullOrWhiteSpace(cleaned))
        {
          return string.Empty;
        }

        if (cleaned.Length == 1)
        {
          return cleaned.ToUpperInvariant();
        }

        return char.ToUpperInvariant(cleaned[0]) + cleaned.Substring(1);
      })
      .Where(x => string.IsNullOrWhiteSpace(x) == false)
      .ToArray();

    var result = string.Concat(parts);
    if (string.IsNullOrWhiteSpace(result))
    {
      result = "KafkaMessage";
    }

    if (char.IsDigit(result[0]))
    {
      result = "_" + result;
    }

    return result;
  }

  private static string EscapeCSharpString(string value)
  {
    return value
      .Replace("\\", "\\\\")
      .Replace("\"", "\\\"");
  }
}