using ModelGenerator.Types;
using Newtonsoft.Json;

namespace ModelGenerator.Core.Tests;

[Trait("Type", "Unit")]
public class ClassGeneratorTests : IDisposable
{
  public ClassGeneratorTests() { }

  public void Dispose() { }

  [Fact]
  public async Task Generate_IfTheSchemaTypeIsJson_ItShouldReturnTheExpectedModelAndRootClassNameAndNormalizedSchema()
  {
    var originalSchema = """
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": [
        "null",
        "string"
      ]
    }
  },
  "title": "KafkaTopicKey",
  "type": "object"
}
""";
    var normalizedSchema = """
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": [
        "null",
        "string"
      ]
    }
  },
  "title": "KafkaTopicKey",
  "type": "object"
}
""";
    var expectedModel = """
// ------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Kafka JSON Schema.
//     Root schema title: KafkaTopicKey
//     This file is intended for use with Confluent.SchemaRegistry.Serdes.Json.
// </auto-generated>
// ------------------------------------------------------------------------------
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace Tester.Models.EopItemTrackingShippingMailV1
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Newtonsoft.Json.JsonObject(Title = "KafkaTopicKey")]
    public partial class KafkaTopicKey
    {

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Id { get; set; } = default!;

    }
}
""";

    Assert.Equal(
      JsonConvert.SerializeObject(new GeneratedOutput
      {
        GeneratedCode = expectedModel,
        NormalizedSchema = normalizedSchema,
        RootClassName = "EopItemTrackingShippingMailV1Key",
      }),
      JsonConvert.SerializeObject(await ClassGenerator.Generate(SchemaTypes.JSON, originalSchema, "Tester.Models.EopItemTrackingShippingMailV1", "EopItemTrackingShippingMailV1Key"))
    );
  }

  [Theory]
  [InlineData("\"title\": \"KafkaTopicKey\",", "EopItemTrackingShippingMailV1Key", "EopItemTrackingShippingMailV1Key")]
  [InlineData("\"title\": \"KafkaTopicKey\",", null, "KafkaTopicKey")]
  [InlineData("\"title\": \"\",", null, "KafkaMessage")]
  [InlineData("", null, "KafkaMessage")]
  public async Task Generate_IfTheSchemaTypeIsJson_ItShouldReturnTheExpectedRootClassName(string schemaTitle, string? explicitRootClassName, string expectedRootClassName)
  {
    var originalSchema = $$"""
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": [
        "null",
        "string"
      ]
    }
  },
  {{schemaTitle}}
  "type": "object"
}
""";

    Assert.Equal(
      expectedRootClassName,
      (await ClassGenerator.Generate(SchemaTypes.JSON, originalSchema, "Tester.Models.EopItemTrackingShippingMailV1", explicitRootClassName)).RootClassName
    );
  }

  [Fact]
  public async Task Generate_IfTheSchemaTypeIsAvro_ItShouldReturnTheExpectedModelAndRootClassNameAndNormalizedSchema()
  {
    var originalSchema = """
{
  "type": "record",
  "name": "OrderCreatedKey",
  "namespace": "Test.Kafka.Events",
  "fields": [
    {
      "name": "orderId",
      "type": "string"
    }
  ]
}
""";
    var normalizedSchema = """
{
  "type": "record",
  "name": "OrderV1Key",
  "namespace": "Test.Kafka.Events",
  "fields": [
    {
      "name": "orderId",
      "type": "string"
    }
  ]
}
""";
    var expectedModel = """
// ------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Kafka AVRO Schema.
//     Root schema title: OrderV1Key
//     This file is intended for use with Confluent.SchemaRegistry.Serdes.Avro.
// </auto-generated>
// ------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tester.Models.OrderV1
{
  using System;
  using System.Collections.Generic;
  using System.Text;
  using global::Avro;
  using global::Avro.Specific;
  
  
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("testhost", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
  public partial class OrderV1Key : global::Avro.Specific.ISpecificRecord
  {
    
    public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(("{\"type\":\"record\",\"name\":\"OrderV1Key\",\"namespace\":\"Tester.Models.OrderV1\",\"fields\"" +
        ":[{\"name\":\"orderId\",\"type\":\"string\"}]}"));
    
    private string _orderId;
    
    public virtual global::Avro.Schema Schema
    {
      get
      {
        return OrderV1Key._SCHEMA;
      }
    }
    
    public string orderId
    {
      get
      {
        return this._orderId;
      }
      set
      {
        this._orderId = value;
      }
    }
    
    public virtual object Get(int fieldPos)
    {
      switch (fieldPos)
			{
			case 0: return this.orderId;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
    }
    
    public virtual void Put(int fieldPos, object fieldValue)
    {
      switch (fieldPos)
			{
			case 0: this.orderId = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
    }
  }
}

""";

    Assert.Equal(
      JsonConvert.SerializeObject(new GeneratedOutput
      {
        GeneratedCode = expectedModel,
        NormalizedSchema = normalizedSchema,
        RootClassName = "OrderV1Key",
      }),
      JsonConvert.SerializeObject(await ClassGenerator.Generate(SchemaTypes.AVRO, originalSchema, "Tester.Models.OrderV1", "OrderV1Key"))
    );
  }

  [Theory]
  [InlineData("\"name\": \"OrderCreatedKey\",", "OrderV1Key", "OrderV1Key")]
  [InlineData("\"name\": \"OrderCreatedKey\",", null, "OrderCreatedKey")]
  [InlineData("\"name\": \"\",", null, "KafkaMessage")]
  [InlineData("", null, "KafkaMessage")]
  public async Task Generate_IfTheSchemaTypeIsAvro_ItShouldReturnTheExpectedRootClassName(string schemaName, string? explicitRootClassName, string expectedRootClassName)
  {
    var originalSchema = $$"""
{
  "type": "record",
  {{schemaName}}
  "namespace": "Test.Kafka.Events",
  "fields": [
    {
      "name": "orderId",
      "type": "string"
    }
  ]
}
""";

    Assert.Equal(
      expectedRootClassName,
      (await ClassGenerator.Generate(SchemaTypes.AVRO, originalSchema, "Tester.Models.OrderV1", explicitRootClassName)).RootClassName
    );
  }
}