using ModelGenerator.Types;
using Newtonsoft.Json;

namespace ModelGenerator.Core.Tests;

[Trait("Type", "Unit")]
public class ClassGeneratorTests : IDisposable
{
  public ClassGeneratorTests() { }

  public void Dispose() { }

  [Fact]
  public async Task GenerateJson_ItShouldReturnTheExpectedModelAndRootClassNameAndNormalizedSchema()
  {
    var originalSchema = """
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": [
        "null",
        "string"
      ]
    }
  },
  "title": "KafkaTopicKey",
  "type": "object"
}
""";
    var normalizedSchema = """
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": [
        "null",
        "string"
      ]
    }
  },
  "title": "KafkaTopicKey",
  "type": "object"
}
""";
    var expectedModel = """
// ------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Kafka JSON Schema.
//     Root schema title: KafkaTopicKey
//     This file is intended for use with Confluent.SchemaRegistry.Serdes.Json.
// </auto-generated>
// ------------------------------------------------------------------------------
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace Tester.Models.EopItemTrackingShippingMailV1
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Newtonsoft.Json.JsonObject(Title = "KafkaTopicKey")]
    public partial class KafkaTopicKey
    {

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Id { get; set; } = default!;

    }
}
""";

    Assert.Equal(
      JsonConvert.SerializeObject(new GeneratedOutput
      {
        GeneratedCode = expectedModel,
        NormalizedSchema = normalizedSchema,
        RootClassName = "EopItemTrackingShippingMailV1Key",
      }),
      JsonConvert.SerializeObject(await ClassGenerator.GenerateJson(originalSchema, "Tester.Models.EopItemTrackingShippingMailV1", "EopItemTrackingShippingMailV1Key"))
    );
  }

  [Theory]
  [InlineData("\"title\": \"KafkaTopicKey\",", "EopItemTrackingShippingMailV1Key", "EopItemTrackingShippingMailV1Key")]
  [InlineData("\"title\": \"KafkaTopicKey\",", null, "KafkaTopicKey")]
  [InlineData("\"title\": \"\",", null, "KafkaMessage")]
  [InlineData("", null, "KafkaMessage")]
  public async Task GenerateJson_ItShouldReturnTheExpectedRootClassName(string schemaTitle, string? explicitRootClassName, string expectedRootClassName)
  {
    var originalSchema = $$"""
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": [
        "null",
        "string"
      ]
    }
  },
  {{schemaTitle}}
  "type": "object"
}
""";

    Assert.Equal(
      expectedRootClassName,
      (await ClassGenerator.GenerateJson(originalSchema, "Tester.Models.EopItemTrackingShippingMailV1", explicitRootClassName)).RootClassName
    );
  }
}
